namespace Microsoft.EntityFrameworkCore.Query;

public class TPCFiltersInheritanceQueryGaussDBTest(TPCFiltersInheritanceQueryGaussDBFixture fixture)
    : TPCFiltersInheritanceQueryTestBase<TPCFiltersInheritanceQueryGaussDBFixture>(fixture);
